# Pandas: grouping

In [1]:
import pandas as pd
import numpy as np

In [2]:
cars = pd.read_csv("Data/vehicles.csv")

In [3]:
cars.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

How many Car models?

In [4]:
cars["Model"].nunique()

3608

Group by the data by the Make  using count function

In [5]:
cars.groupby("Make").count()

,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
Make,,,,,,,,,,,,,,
AM General,4,4,4,4,4,4,4,4,4,4,4,4,4,4
ASC Incorporated,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Acura,302,302,302,302,302,302,302,302,302,302,302,302,302,302
Alfa Romeo,41,41,41,41,41,41,41,41,41,41,41,41,41,41
American Motors Corporation,22,22,22,22,22,22,22,22,22,22,22,22,22,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Volkswagen,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047
Volvo,717,717,717,717,717,717,717,717,717,717,717,717,717,717
Wallace Environmental,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Yugo,8,8,8,8,8,8,8,8,8,8,8,8,8,8
smart,20,20,20,20,20,20,20,20,20,20,20,20,20,20

What brand has the most cars?

In [6]:
cars["Make"].value_counts().idxmax()

'Chevrolet'

<b>show the average CO2_Emission_Grams/Km  by Brand

In [7]:
# I will convert Grams/Mile to Grams/Km

cars["CO2 Emission Grams/Km"] = cars["CO2 Emission Grams/Mile"] / 1.60934

cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048

In [8]:
# And now calculating the average by brand.

brand_co2 = cars.groupby("Make")["CO2 Emission Grams/Km"].apply(lambda x: x.mean() )

In [9]:
brand_co2

Make
AM General                     379.881345
ASC Incorporated               345.133719
Acura                          262.583000
Alfa Romeo                     288.287195
American Motors Corporation    314.264744
                                  ...
Volkswagen                     244.038998
Volvo                          270.796572
Wallace Environmental          408.857065
Yugo                           221.251107
smart                          153.498052
Name: CO2 Emission Grams/Km, Length: 127, dtype: float64

<b>show the average CO2_Emission_Grams/Km  by Brand ... sorted

In [10]:
brand_co2.sort_values()

Make
Fisker                                105.011992
smart                                 153.498052
Fiat                                  189.311494
Daihatsu                              192.742404
MINI                                  194.935105
                                         ...
Laforza Automobile Inc                502.012683
Bugatti                               542.497235
Superior Coaches Div E.p. Dutton      552.213951
S and S Coach Company  E.p. Dutton    552.213951
Vector                                651.919248
Name: CO2 Emission Grams/Km, Length: 127, dtype: float64

Use `pd.cut` or `pd.qcut` to create 4 groups (bins) of cars, by Year. We want to explore how cars have evolved decade by decade.

In [11]:
cars['Year'].describe()

count    35952.00000
mean      2000.71640
std         10.08529
min       1984.00000
25%       1991.00000
50%       2001.00000
75%       2010.00000
max       2017.00000
Name: Year, dtype: float64

In [12]:
cars["Decade"] = pd.cut(x = cars["Year"], bins = [1980, 1990, 2000, 2010, 2020], labels = ["80's", "90's", "00's", "10's"]) 

cars.Decade.unique()

['80's', '90's', '00's', '10's']
Categories (4, object): ['80's' < '90's' < '00's' < '10's']

In [13]:
cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Decade
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736,80's
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719,80's
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719,80's
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575,10's
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693,10's
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048,10's

### Did cars consume more gas in the eighties?

show the average City_Km/Liter by year_range

In [14]:
# I will convert City MPG to Km/Liter

cars["City Km/Liter"] = cars["City MPG"] * 0.42514

cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Decade,City Km/Liter
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736,80's,7.65252
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's,5.52682
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719,80's,6.80224
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's,5.52682
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719,80's,5.95196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's,14.45476
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575,10's,14.45476
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's,14.45476
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693,10's,14.45476
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048,10's,13.60448

In [15]:
# Calculating the usage for every decade.

cars.groupby("Decade")["City Km/Liter"].apply(lambda x: x.mean() )

Decade
80's    7.349783
90's    7.204150
00's    7.208365
10's    8.394374
Name: City Km/Liter, dtype: float64

Which brands are more environment friendly?

In [16]:
env_friendl = cars.groupby(["Decade", "Make"])["CO2 Emission Grams/Km"].apply(lambda x: x.mean())
env_friendl

Decade  Make
80's    AM General                     379.881345
        ASC Incorporated               345.133719
        Acura                          264.463085
        Alfa Romeo                     288.426326
        American Motors Corporation    314.264744
                                          ...
10's    Volkswagen                     214.410174
        Volvo                          242.932543
        Wallace Environmental                 NaN
        Yugo                                  NaN
        smart                          153.543176
Name: CO2 Emission Grams/Km, Length: 508, dtype: float64

Does the drivetrain affect fuel consumption?

In [17]:
# Converting Highway MPG to Km/Liter

cars["Highway Km/Liter"] = cars["Highway MPG"] * 0.42514
cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,CO2 Emission Grams/Km,Decade,City Km/Liter,Highway Km/Liter
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,324.831736,80's,7.65252,7.22738
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's,5.52682,5.52682
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,345.133719,80's,6.80224,7.22738
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,424.779962,80's,5.52682,5.52682
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,345.133719,80's,5.95196,8.92794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's,14.45476,16.15532
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100,150.993575,10's,14.45476,16.15532
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100,151.614948,10's,14.45476,16.15532
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100,152.857693,10's,14.45476,16.58046
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150,158.450048,10's,13.60448,16.58046

In [18]:
# Calculating the mean for every type of drivetrain.

cars.groupby("Drivetrain")["Highway Km/Liter", "City Km/Liter"].apply(lambda x: x.mean())

/var/folders/5w/01d7vm4j0msggtd01phb8l600000gn/T/ipykernel_5455/2880131270.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  cars.groupby("Drivetrain")["Highway Km/Liter", "City Km/Liter"].apply(lambda x: x.mean())

                            Highway Km/Liter  City Km/Liter
Drivetrain
2-Wheel Drive                       8.222389       6.642436
2-Wheel Drive, Front               14.029620      10.628500
4-Wheel Drive                       9.668519       7.190813
4-Wheel or All-Wheel Drive          8.347074       6.392006
All-Wheel Drive                    10.882458       7.785546
Front-Wheel Drive                  12.166129       9.002154
Part-time 4-Wheel Drive             8.115331       6.215654
Rear-Wheel Drive                    9.023885       6.556530

Do cars with automatic transmission consume more fuel than cars with manual transmission?

In [19]:
# Changing the values for transmission column, so that they will be more clear - automatic or manual.

def transmission_renaming(x):
    if x.startswith("A"):
        return "Automatic"
    else:
        return "Manual"

In [20]:
cars["Transmission"] = list(map(transmission_renaming, cars["Transmission"]))

In [21]:
cars["Transmission"].unique()

array(['Automatic', 'Manual'], dtype=object)

In [22]:
# Calculating the fuel consumption mean for both transmission type.

cars.groupby("Transmission")["Highway Km/Liter", "City Km/Liter"].apply(lambda x: x.mean())

/var/folders/5w/01d7vm4j0msggtd01phb8l600000gn/T/ipykernel_5455/3754533302.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  cars.groupby("Transmission")["Highway Km/Liter", "City Km/Liter"].apply(lambda x: x.mean())

              Highway Km/Liter  City Km/Liter
Transmission
Automatic             9.882413       7.278243
Manual               10.715409       7.968295

Use `groupby` and `aggregate` with different aggregation measures for different columns:

aggregate with average City_Km/Liter and the count of the Trans

In [23]:
cars.groupby("Transmission").agg({"City Km/Liter" : ["mean"], "Transmission" : ["count"]})

             City Km/Liter Transmission
                      mean        count
Transmission
Automatic         7.278243        24290
Manual            7.968295        11662

aggregate with average City_Km/Liter and the minimum of the Trans

In [28]:
cars.groupby("Transmission").agg({"City Km/Liter" : ["mean", "min"]})

             City Km/Liter
                      mean      min
Transmission
Automatic         7.278243  2.97598
Manual            7.968295  2.55084